// Generated by CoffeeScript 1.4.0

Ext.Loader.setConfig({
  enabled: true,
  paths: {
	"Ext":"../js/lib/ext/src",
    "deftApp": "app5"
  }
});
Ext.syncRequire(["Ext.Component", "Ext.ComponentManager", "Ext.ComponentQuery"]);