DROP TABLE IF EXISTS PUBLIC.ADDRESS;
CREATE TABLE PUBLIC.ADDRESS(
ID INTEGER NOT NULL,
ADDRESS  varchar(255),
LATITUDE varchar(255),
LONGITUDE varchar(255),
ABBREVIATION varchar(255),
CITY varchar(255),
CONSTRAINT ADDRESS_PKEY_ID PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS PUBLIC.METER;
CREATE TABLE PUBLIC.METER(
ID INTEGER NOT NULL,
CODE varchar(255),
LATITUDE varchar(255),
LONGITUDE varchar(255),
CONSTRAINT METER_PKEY_ID PRIMARY KEY(ID)
);


DROP TABLE IF EXISTS PUBLIC.METER_ADDRESS;
CREATE TABLE PUBLIC.METER_ADDRESS(
METER_ID INTEGER NOT NULL REFERENCES METER(ID),
ADDRESS_ID INTEGER NOT NULL REFERENCES ADDRESS(ID),
CONSTRAINT METER_PKEY_ID PRIMARY KEY(METER_ID,ADDRESS_ID)

);