DROP SEQUENCE IF EXISTS public.ADDRESS_SEQ; CREATE SEQUENCE public.ADDRESS_SEQ START WITH 1 INCREMENT BY 1;
DROP SEQUENCE IF EXISTS public.METER_SEQ; CREATE SEQUENCE public.METER_SEQ START WITH 1 INCREMENT BY 1;
